# Generated by Django 2.1.3 on 2019-04-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='companies/%Y/%m/%d')),
                ('location', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('ict', 'ICT')], max_length=10)),
                ('about', models.CharField(max_length=450)),
                ('services', models.CharField(max_length=450)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
