# Generated by Django 2.1 on 2019-09-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('account', '0006_remove_profile_registration_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees_reg_centres', to='registration.RegistrationCentre'),
        ),
    ]
