# Generated by Django 2.1 on 2019-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthregistration',
            name='id_no',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
