# Generated by Django 2.1 on 2019-11-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20191002_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthregistration',
            name='birth_cert_no',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='deathregistration',
            name='death_cert_no',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='deathregistration',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='registration.BirthRegistration'),
        ),
    ]
