# Generated by Django 2.2.5 on 2019-11-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20191112_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthregistration',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deathregistration',
            name='date_of_death',
            field=models.DateTimeField(),
        ),
    ]
