# Generated by Django 2.2.5 on 2019-11-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20191113_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathregistration',
            name='cause_of_death',
        ),
        migrations.RemoveField(
            model_name='deathregistration',
            name='occupation',
        ),
    ]
