# Generated by Django 2.2.5 on 2019-11-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20191113_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathregistration',
            name='cause_of_death',
            field=models.CharField(default='Malaria', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deathregistration',
            name='occupation',
            field=models.CharField(default='Teacher', max_length=300),
            preserve_default=False,
        ),
    ]
