# Generated by Django 2.2.5 on 2019-11-27 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20191113_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthregistration',
            name='constituency',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_constituency', message='Constituency must be in Character format', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='fathers_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_fathers_name', message='Fathers name must be in Character format', regex='^[A-Za-z ]*$')]),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='first_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='First Name must be in Character format', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='id_no',
            field=models.CharField(blank=True, default='exit', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_constituency', message='Id Number must be in Numbers only', regex='^[0-9]*$'), django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(7)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='middle_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_middle_name', message='Middle Name must be in Character format', regex='^[a-zA-Z ]*$')]),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='mothers_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_mothers_name', message='Mothers name must be in Character format', regex='^[A-Za-z ]*$')]),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='surname',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_surname', message='Surname must be in Character format', regex='^[a-zA-Z ]*$')]),
        ),
        migrations.AlterField(
            model_name='deathregistration',
            name='cause_of_death',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_cause_of_death', message='Cause of death must be in Character format', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='deathregistration',
            name='current_constituency',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_current_constituency', message='Current Constituency must be in Character format', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='deathregistration',
            name='occupation',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_occupation', message='Occupation must be in Character format', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='registrationcentre',
            name='reg_centre_email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Enter correct email format', regex='(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)')]),
        ),
        migrations.AlterField(
            model_name='registrationcentre',
            name='reg_centre_location',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_reg_centre_location', message='Registration Centre location must be in Character format', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='registrationcentre',
            name='reg_centre_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_reg_centre_name', message='Registration centre name must be in Character format', regex='^[a-zA-Z]*$')]),
        ),
    ]
