# Generated by Django 2.2.5 on 2019-11-28 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20191127_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthregistration',
            name='constituency',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_constituency', message='Constituency must be in Character format', regex='^[A-Za-z ]*$')]),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='first_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='First Name must be in Character format', regex='^[A-Za-z ]*$')]),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='middle_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_middle_name', message='Middle Name must be in Character format', regex='^[A-Za-z ]*$')]),
        ),
        migrations.AlterField(
            model_name='birthregistration',
            name='surname',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_surname', message='Surname must be in Character format', regex='^[A-Za-z ]*$')]),
        ),
        migrations.AlterField(
            model_name='deathregistration',
            name='cause_of_death',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_cause_of_death', message='Cause of death must be in Character format', regex='^[A-Za-z ]*$')]),
        ),
        migrations.AlterField(
            model_name='deathregistration',
            name='current_constituency',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_current_constituency', message='Current Constituency must be in Character format', regex='^[A-Za-z ]*$')]),
        ),
        migrations.AlterField(
            model_name='deathregistration',
            name='occupation',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_occupation', message='Occupation must be in Character format', regex='^[A-Za-z ]*$')]),
        ),
    ]
